{
    "title": "New OTHER TRANSACTION IDV HR00112390011 awarded to PHAEDRUS LLC for the amount of $0",
    "contract_type": "OTHERTRANSACTIONIDV",
    "link__rel": "alternate",
    "link__type": "text/html",
    "link__href": "https://www.fpds.gov/ezsearch/search.do?s=FPDS&indexName=awardfull&templateName=1.5.3&q=HR00112390011+9700+",
    "modified": "2023-01-04 16:46:15",
    "content": "\n      ",
    "content__type": "application/xml",
    "content__OtherTransactionIDV": "\n        ",
    "content__OtherTransactionIDV__version": "1.5",
    "content__OtherTransactionIDV__OtherTransactionIDVID": "\n          ",
    "content__OtherTransactionIDV__OtherTransactionIDVID__OtherTransactionIDVContractID": "\n            ",
    "content__OtherTransactionIDV__OtherTransactionIDVID__OtherTransactionIDVContractID__agencyID": "9700",
    "content__OtherTransactionIDV__OtherTransactionIDVID__OtherTransactionIDVContractID__agencyID__name": "DEPT OF DEFENSE",
    "content__OtherTransactionIDV__OtherTransactionIDVID__OtherTransactionIDVContractID__PIID": "HR00112390011",
    "content__OtherTransactionIDV__OtherTransactionIDVID__OtherTransactionIDVContractID__modNumber": "0",
    "content__OtherTransactionIDV__contractDetail": "\n          ",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates": "\n            ",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates__signedDate": "2023-01-04 00:00:00",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates__effectiveDate": "2023-01-04 00:00:00",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates__currentCompletionDate": "2028-01-04 00:00:00",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates__ultimateCompletionDate": "2028-01-04 00:00:00",
    "content__OtherTransactionIDV__contractDetail__relevantContractDates__fiscalYear": "2023",
    "content__OtherTransactionIDV__contractDetail__dollarValues": "\n            ",
    "content__OtherTransactionIDV__contractDetail__dollarValues__obligatedAmount": "0.00",
    "content__OtherTransactionIDV__contractDetail__dollarValues__baseAndExercisedOptionsValue": "150000000.00",
    "content__OtherTransactionIDV__contractDetail__dollarValues__baseAndAllOptionsValue": "150000000.00",
    "content__OtherTransactionIDV__contractDetail__dollarValues__nonGovernmentalDollars": "0.00",
    "content__OtherTransactionIDV__contractDetail__totalDollarValues": "\n            ",
    "content__OtherTransactionIDV__contractDetail__totalDollarValues__totalObligatedAmount": "125715371.00",
    "content__OtherTransactionIDV__contractDetail__totalDollarValues__totalBaseAndExercisedOptionsValue": "490000000.00",
    "content__OtherTransactionIDV__contractDetail__totalDollarValues__totalBaseAndAllOptionsValue": "490000000.00",
    "content__OtherTransactionIDV__contractDetail__totalDollarValues__totalNonGovernmentalDollars": "0.00",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation": "\n            ",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeAgencyID": "97AE",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeAgencyID__name": "DEFENSE ADVANCED RESEARCH PROJECTS AGENCY  (DARPA)",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeAgencyID__departmentID": "9700",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeAgencyID__departmentName": "DEPT OF DEFENSE",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeID": "HR0011",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeID__name": "DEF ADVANCED RESEARCH PROJECTS AGCY",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__contractingOfficeID__country": "USA",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingAgencyID": "97AE",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingAgencyID__name": "DEFENSE ADVANCED RESEARCH PROJECTS AGENCY  (DARPA)",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingAgencyID__departmentID": "9700",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingAgencyID__departmentName": "DEPT OF DEFENSE",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingOfficeID": "HR0011",
    "content__OtherTransactionIDV__contractDetail__purchaserInformation__fundingRequestingOfficeID__name": "DEF ADVANCED RESEARCH PROJECTS AGCY",
    "content__OtherTransactionIDV__contractDetail__contractData": "\n            ",
    "content__OtherTransactionIDV__contractDetail__contractData__contractActionType": "O",
    "content__OtherTransactionIDV__contractDetail__contractData__contractActionType__description": "OTHER TRANSACTION IDV",
    "content__OtherTransactionIDV__contractDetail__contractData__typeOfAgreement": "PROTOTYPE",
    "content__OtherTransactionIDV__contractDetail__contractData__descriptionOfContractRequirement": "CONSTELLATION PROTOTYPE AGREEMENT",
    "content__OtherTransactionIDV__contractDetail__contractData__nonTraditionalGovernmentContractorParticipation": "NSP",
    "content__OtherTransactionIDV__contractDetail__contractData__nonTraditionalGovernmentContractorParticipation__description": "NONTRADITIONAL SIGNIFICANT PARTICIPATION",
    "content__OtherTransactionIDV__contractDetail__PSCCode": "AC12",
    "content__OtherTransactionIDV__contractDetail__PSCCode__description": "NATIONAL DEFENSE R&D SERVICES; DEPARTMENT OF DEFENSE - MILITARY; APPLIED RESEARCH",
    "content__OtherTransactionIDV__contractDetail__PSCCode__productOrServiceType": "SERVICE",
    "content__OtherTransactionIDV__contractDetail__vendor": "\n            ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorHeader": "\n              ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorHeader__vendorName": "PHAEDRUS LLC",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails": "\n              ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isAlaskanNativeOwnedCorporationOrFirm": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isAmericanIndianOwned": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isIndianTribe": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isNativeHawaiianOwnedOrganizationOrFirm": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isTriballyOwnedFirm": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isSmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isVeteranOwned": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isServiceRelatedDisabledVeteranOwnedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isWomenOwned": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isMinorityOwned": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isSubContinentAsianAmericanOwnedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isAsianPacificAmericanOwnedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isBlackAmericanOwnedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isHispanicAmericanOwnedBusiness": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isNativeAmericanOwnedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__minorityOwned__isOtherMinorityOwned": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isVerySmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isWomenOwnedSmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isEconomicallyDisadvantagedWomenOwnedSmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isJointVentureWomenOwnedSmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorSocioEconomicIndicators__isJointVentureEconomicallyDisadvantagedWomenOwnedSmallBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__isCommunityDevelopedCorporationOwnedFirm": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__isLaborSurplusAreaFirm": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__federalGovernment": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__federalGovernment__isFederalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__federalGovernment__isFederallyFundedResearchAndDevelopmentCorp": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__federalGovernment__isFederalGovernmentAgency": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__isStateGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isCityLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isCountyLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isInterMunicipalLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isLocalGovernmentOwned": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isMunicipalityLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isSchoolDistrictLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__localGovernment__isTownshipLocalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__isTribalGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__isForeignGovernment": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isCorporateEntityNotTaxExempt": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isCorporateEntityTaxExempt": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isPartnershipOrLimitedLiabilityPartnership": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isSolePropreitorship": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isSmallAgriculturalCooperative": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isInternationalOrganization": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorBusinessTypes__businessOrOrganizationType__isUSGovernmentEntity": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isCommunityDevelopmentCorporation": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isDomesticShelter": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isEducationalInstitution": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isFoundation": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isHospital": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isManufacturerOfGoods": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isVeterinaryHospital": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLineOfBusiness__isHispanicServicingInstitution": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorRelationshipWithFederalGovernment": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorRelationshipWithFederalGovernment__receivesContracts": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorRelationshipWithFederalGovernment__receivesGrants": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorRelationshipWithFederalGovernment__receivesContractsAndGrants": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isAirportAuthority": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isCouncilOfGovernments": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isHousingAuthoritiesPublicOrTribal": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isInterstateEntity": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isPlanningCommission": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isPortAuthority": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfGovernmentEntity__isTransitAuthority": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__isSubchapterSCorporation": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__isLimitedLiabilityCorporation": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__isForeignOwnedAndLocated": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__profitStructure": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__profitStructure__isForProfitOrganization": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__profitStructure__isNonprofitOrganization": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__profitStructure__isOtherNotForProfitOrganization": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__isShelteredWorkshop": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__stateOfIncorporation": "MD",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__stateOfIncorporation__name": "MARYLAND",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__countryOfIncorporation": "USA",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__countryOfIncorporation__name": "UNITED STATES",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorOrganizationFactors__organizationalType": "CORPORATE NOT TAX EXEMPT",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__is1862LandGrantCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__is1890LandGrantCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__is1994LandGrantCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isHistoricallyBlackCollegeOrUniversity": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isMinorityInstitution": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isPrivateUniversityOrCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isSchoolOfForestry": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isStateControlledInstitutionofHigherLearning": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isTribalCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isVeterinaryCollege": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isAlaskanNativeServicingInstitution": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__typeOfEducationalEntity__isNativeHawaiianServicingInstitution": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isDOTCertifiedDisadvantagedBusinessEnterprise": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSelfCertifiedSmallDisadvantagedBusiness": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSBACertifiedSmallDisadvantagedBusiness": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSBACertified8AProgramParticipant": "true",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSelfCertifiedHUBZoneJointVenture": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSBACertifiedHUBZone": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorCertifications__isSBACertified8AJointVenture": "false",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__streetAddress": "2801 SOMMERSBY RD",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__city": "MOUNT AIRY",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__state": "MD",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__state__name": "MARYLAND",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__ZIPCode": "217718049",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__ZIPCode__city": "MOUNT AIRY",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__countryCode": "USA",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__countryCode__name": "UNITED STATES",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__phoneNo": "2103635648",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__congressionalDistrictCode": "08",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorLocation__entityDataSource": "E&Y",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__vendorAlternateSiteCode": "21771",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__vendorUEIInformation": "\n                  ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__vendorUEIInformation__UEI": "FAQVMKLKFG31",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__vendorUEIInformation__UEILegalBusinessName": "PHAEDRUS LLC",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__vendorUEIInformation__ultimateParentUEI": "FAQVMKLKFG31",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__vendorUEIInformation__ultimateParentUEIName": "PHAEDRUS LLC",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__entityIdentifiers__cageCode": "8FKM8",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__ccrRegistrationDetails": "\n                ",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__ccrRegistrationDetails__registrationDate": "2019-11-20 00:00:00",
    "content__OtherTransactionIDV__contractDetail__vendor__vendorSiteDetails__ccrRegistrationDetails__renewalDate": "2023-11-03 00:00:00",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation": "\n            ",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__consortiaFlag": "Y",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaMemberUEI": "FAQVMKLKFG31",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaMemberName": "PHAEDRUS LLC",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaMemberCageCode": "8FKM8",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation": "\n              ",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__streetAddress1": "2801 SOMMERSBY RD",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__city": "MOUNT AIRY",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__state": "MD",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__ZIPCode": "21771-8049",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__congressionalDistrictCode": "08",
    "content__OtherTransactionIDV__contractDetail__consortiaInformation__primaryConsortiaLocation__countryCode": "USA",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance": "\n            ",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__principalPlaceOfPerformance": "\n              ",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__principalPlaceOfPerformance__stateCode": "MD",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__principalPlaceOfPerformance__stateCode__name": "MARYLAND",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__principalPlaceOfPerformance__countryCode": "USA",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__principalPlaceOfPerformance__countryCode__name": "UNITED STATES",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__placeOfPerformanceZIPCode": "217718049",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__placeOfPerformanceZIPCode__county": "FREDERICK",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__placeOfPerformanceZIPCode__city": "MOUNT AIRY",
    "content__OtherTransactionIDV__contractDetail__placeOfPerformance__placeOfPerformanceCongressionalDistrict": "08",
    "content__OtherTransactionIDV__contractDetail__competition": "\n            ",
    "content__OtherTransactionIDV__contractDetail__competition__solicitationProcedures": "SSS",
    "content__OtherTransactionIDV__contractDetail__competition__solicitationProcedures__description": "ONLY ONE SOURCE",
    "content__OtherTransactionIDV__contractDetail__competition__extentCompeted": "C",
    "content__OtherTransactionIDV__contractDetail__competition__extentCompeted__description": "NOT COMPETED",
    "content__OtherTransactionIDV__contractDetail__transactionInformation": "\n            ",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__createdBy": "JOSEPH.STEINBERGER.CTR.HR0011@DARPA.MIL",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__createdDate": "2023-01-04 15:54:45",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__lastModifiedBy": "JOSEPH.STEINBERGER.HR0011@SA97AE.DARPA",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__lastModifiedDate": "2023-01-04 16:46:15",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__status": "F",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__status__description": "FINAL",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__approvedBy": "JOSEPH.STEINBERGER.CTR.HR0011@DARPA.MIL",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__approvedDate": "2023-01-04 16:34:13",
    "content__OtherTransactionIDV__contractDetail__transactionInformation__closedStatus": "N",
    "content__OtherTransactionIDV__genericTags": "\n          ",
    "content__OtherTransactionIDV__genericTags__genericStrings": "\n            ",
    "content__OtherTransactionIDV__genericTags__genericStrings__genericString01": "2022-09-21 00:00:00",
    "content__OtherTransactionIDV__genericTags__genericStrings__genericString02": "FAQVMKLKFG31",
    "content__OtherTransactionIDV__genericTags__genericStrings__genericString04": "Y",
    "content__OtherTransactionIDV__genericTags__genericStrings__genericString05": "FAQVMKLKFG31"
}