"""create contracts table with partitioning

Revision ID: 05577f7a0d74
Revises: 
Create Date: 2025-02-15 17:35:00.588374
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05577f7a0d74'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    """Create contracts table with partitioning by year."""

    # Создаем партиционированную таблицу с комментариями и индексами
    op.execute("""
        CREATE TABLE contracts (
            id BIGINT AUTO_INCREMENT COMMENT 'Primary key',
            partition_year YEAR NOT NULL COMMENT 'Year used for partitioning',
            agency_id VARCHAR(255) COMMENT 'Unique identifier for the agency that awarded the contract',
            contract_type VARCHAR(255) COMMENT 'The type of contract (e.g., IDV, AWARD, OTHERTRANSACTIONAWARD)',
            piid VARCHAR(255) COMMENT 'Procurement Instrument Identifier (PIID)',
            mod_number VARCHAR(255) COMMENT 'Modification number of the award or contract',
            idv_piid VARCHAR(255) COMMENT 'The PIID of the IDV contract if applicable',
            referenced_piid VARCHAR(255) COMMENT 'The PIID for the referenced award or contract',
            signed_date DATE COMMENT 'The date the contract was signed',
            effective_date DATE COMMENT 'The effective start date of the contract',
            ultimate_completion_date DATE COMMENT 'The final completion date of the contract, including any extensions',
            last_date_to_order DATE COMMENT 'The last date by which orders can be placed under this IDV contract',
            obligated_amount DECIMAL(15,2) COMMENT 'The obligated amount of funds for the contract',
            base_and_all_options_value DECIMAL(15,2) COMMENT 'The value of base and all options',
            total_obligated_amount DECIMAL(15,2) COMMENT 'The total amount of funds obligated under the contract',
            total_base_and_all_options_value DECIMAL(15,2) COMMENT 'The total value of the contract, including options',
            contracting_office_agency_id VARCHAR(255) COMMENT 'The ID of the contracting office agency',
            contracting_office_id VARCHAR(255) COMMENT 'The ID of the contracting office',
            funding_requesting_agency_id VARCHAR(255) COMMENT 'The ID of the funding or requesting agency',
            funding_requesting_office_id VARCHAR(255) COMMENT 'The ID of the funding or requesting office',
            contract_action_type_description VARCHAR(255) COMMENT 'Description of the type of contract action',
            type_of_contract_pricing_description VARCHAR(255) COMMENT 'Description of the contract pricing type',
            description_of_contract_requirement TEXT COMMENT 'Description of the contract requirement and scope',
            multi_year_contract VARCHAR(255) COMMENT 'Indicates whether the contract is multi-year',
            referenced_idv_multiple_or_single VARCHAR(255) COMMENT 'Indicates whether the referenced IDV contract is for a single or multiple awards',
            referenced_idv_type VARCHAR(255) COMMENT 'The type of the referenced IDV contract',
            labor_standards VARCHAR(255) COMMENT 'Indicates whether labor standards apply to the contract',
            psc_code VARCHAR(255) COMMENT 'The product or service code',
            psc_type VARCHAR(255) COMMENT 'Indicates whether the contract is for a product or a service',
            naics_code VARCHAR(255) COMMENT 'The principal NAICS code',
            country_of_origin VARCHAR(255) COMMENT 'The country of origin of the goods or services provided',
            vendor_name VARCHAR(255) COMMENT 'The official name of the vendor or contractor awarded the contract',
            is_small_business BOOLEAN COMMENT 'Indicates whether the vendor is a small business',
            is_veteran_owned_business BOOLEAN COMMENT 'Indicates whether the vendor is a veteran-owned business',
            is_women_owned_business BOOLEAN COMMENT 'Indicates whether the vendor is a women-owned business',
            is_very_small_business BOOLEAN COMMENT 'Indicates whether the vendor is classified as a very small business',
            is_women_owned_small_business BOOLEAN COMMENT 'Indicates whether the vendor is a women-owned small business',
            is_economically_disadvantaged_women_owned_small_business BOOLEAN COMMENT 'Indicates whether the vendor is an economically disadvantaged women-owned small business',
            is_partnership_or_limited_liability_partnership BOOLEAN COMMENT 'Indicates whether the vendor is a partnership or limited liability partnership',
            receives_contracts_and_grants BOOLEAN COMMENT 'Indicates whether the vendor receives both contracts and grants',
            is_for_profit_organization BOOLEAN COMMENT 'Indicates whether the vendor is a for-profit organization',
            vendor_state_of_incorporation VARCHAR(255) COMMENT 'The state where the vendor is incorporated',
            vendor_country_of_incorporation VARCHAR(255) COMMENT 'The country where the vendor is incorporated',
            vendor_location_street_address VARCHAR(255) COMMENT 'The street address where the vendor is located',
            vendor_location_city VARCHAR(255) COMMENT 'The city where the vendor is located',
            vendor_location_state VARCHAR(255) COMMENT 'The state where the vendor is located',
            vendor_location_zipcode VARCHAR(255) COMMENT 'The ZIP code of the vendor''s location',
            vendor_location_country VARCHAR(255) COMMENT 'The country where the vendor is located',
            vendor_uei VARCHAR(255) COMMENT 'The Unique Entity Identifier (UEI) of the vendor',
            vendor_ultimate_parent_uei VARCHAR(255) COMMENT 'The Unique Entity Identifier (UEI) of the vendor''s ultimate parent company',
            vendor_cage_code VARCHAR(255) COMMENT 'The CAGE code of the vendor',
            vendor_registration_date DATE COMMENT 'The date when the vendor was registered',
            vendor_renewal_date DATE COMMENT 'The date when the vendor''s registration was last renewed',
            vendor_size VARCHAR(255) COMMENT 'The size classification of the vendor',
            place_of_performance_state VARCHAR(255) COMMENT 'The state where the contract work will be performed',
            place_of_performance_country VARCHAR(255) COMMENT 'The country where the contract work will be performed',
            place_of_performance_zip VARCHAR(255) COMMENT 'The ZIP code where the contract work will be performed',
            competition_extent_competed VARCHAR(255) COMMENT 'Indicates the extent of competition for the contract',
            competition_solicitation_procedures VARCHAR(255) COMMENT 'Describes the solicitation procedures used for the contract',
            competition_reason_not_competed VARCHAR(255) COMMENT 'Reason why the contract was not competed',
            competition_number_of_offers_received VARCHAR(255) COMMENT 'The number of offers received for the contract',
            competition_idv_number_of_offers_received VARCHAR(255) COMMENT 'The number of offers received for the IDV contract',
            competition_fed_biz_opps VARCHAR(255) COMMENT 'Indicates whether the contract was posted on FedBizOpps',
            award_transaction_information_status VARCHAR(255) COMMENT 'The status of the contract transaction',
            file_path VARCHAR(255) COMMENT 'The file path to the stored file data',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp of record creation',
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp of last update',
            PRIMARY KEY (id, partition_year),
            INDEX (partition_year),
            INDEX (agency_id),
            INDEX (piid),
            INDEX (contract_type)
        )
        PARTITION BY RANGE (partition_year) (
            PARTITION p1957 VALUES LESS THAN (1958),
            PARTITION p1958 VALUES LESS THAN (1959),
            PARTITION p1959 VALUES LESS THAN (1960),
            PARTITION p1960 VALUES LESS THAN (1961),
            PARTITION p1961 VALUES LESS THAN (1962),
            PARTITION p1962 VALUES LESS THAN (1963),
            PARTITION p1963 VALUES LESS THAN (1964),
            PARTITION p1964 VALUES LESS THAN (1965),
            PARTITION p1965 VALUES LESS THAN (1966),
            PARTITION p1966 VALUES LESS THAN (1967),
            PARTITION p1967 VALUES LESS THAN (1968),
            PARTITION p1968 VALUES LESS THAN (1969),
            PARTITION p1969 VALUES LESS THAN (1970),
            PARTITION p1970 VALUES LESS THAN (1971),
            PARTITION p1971 VALUES LESS THAN (1972),
            PARTITION p1972 VALUES LESS THAN (1973),
            PARTITION p1973 VALUES LESS THAN (1974),
            PARTITION p1974 VALUES LESS THAN (1975),
            PARTITION p1975 VALUES LESS THAN (1976),
            PARTITION p1976 VALUES LESS THAN (1977),
            PARTITION p1977 VALUES LESS THAN (1978),
            PARTITION p1978 VALUES LESS THAN (1979),
            PARTITION p1979 VALUES LESS THAN (1980),
            PARTITION p1980 VALUES LESS THAN (1981),
            PARTITION p1981 VALUES LESS THAN (1982),
            PARTITION p1982 VALUES LESS THAN (1983),
            PARTITION p1983 VALUES LESS THAN (1984),
            PARTITION p1984 VALUES LESS THAN (1985),
            PARTITION p1985 VALUES LESS THAN (1986),
            PARTITION p1986 VALUES LESS THAN (1987),
            PARTITION p1987 VALUES LESS THAN (1988),
            PARTITION p1988 VALUES LESS THAN (1989),
            PARTITION p1989 VALUES LESS THAN (1990),
            PARTITION p1990 VALUES LESS THAN (1991),
            PARTITION p1991 VALUES LESS THAN (1992),
            PARTITION p1992 VALUES LESS THAN (1993),
            PARTITION p1993 VALUES LESS THAN (1994),
            PARTITION p1994 VALUES LESS THAN (1995),
            PARTITION p1995 VALUES LESS THAN (1996),
            PARTITION p1996 VALUES LESS THAN (1997),
            PARTITION p1997 VALUES LESS THAN (1998),
            PARTITION p1998 VALUES LESS THAN (1999),
            PARTITION p1999 VALUES LESS THAN (2000),
            PARTITION p2000 VALUES LESS THAN (2001),
            PARTITION p2001 VALUES LESS THAN (2002),
            PARTITION p2002 VALUES LESS THAN (2003),
            PARTITION p2003 VALUES LESS THAN (2004),
            PARTITION p2004 VALUES LESS THAN (2005),
            PARTITION p2005 VALUES LESS THAN (2006),
            PARTITION p2006 VALUES LESS THAN (2007),
            PARTITION p2007 VALUES LESS THAN (2008),
            PARTITION p2008 VALUES LESS THAN (2009),
            PARTITION p2009 VALUES LESS THAN (2010),
            PARTITION p2010 VALUES LESS THAN (2011),
            PARTITION p2011 VALUES LESS THAN (2012),
            PARTITION p2012 VALUES LESS THAN (2013),
            PARTITION p2013 VALUES LESS THAN (2014),
            PARTITION p2014 VALUES LESS THAN (2015),
            PARTITION p2015 VALUES LESS THAN (2016),
            PARTITION p2016 VALUES LESS THAN (2017),
            PARTITION p2017 VALUES LESS THAN (2018),
            PARTITION p2018 VALUES LESS THAN (2019),
            PARTITION p2019 VALUES LESS THAN (2020),
            PARTITION p2020 VALUES LESS THAN (2021),
            PARTITION p2021 VALUES LESS THAN (2022),
            PARTITION p2022 VALUES LESS THAN (2023),
            PARTITION p2023 VALUES LESS THAN (2024),
            PARTITION p2024 VALUES LESS THAN (2025),
            PARTITION p2025 VALUES LESS THAN (2026),
            PARTITION p2026 VALUES LESS THAN (2027),
            PARTITION p2027 VALUES LESS THAN (2028),
            PARTITION p2028 VALUES LESS THAN (2029),
            PARTITION p2029 VALUES LESS THAN (2030),
            PARTITION p2030 VALUES LESS THAN (2031),
            PARTITION p2031 VALUES LESS THAN (2032),
            PARTITION p2032 VALUES LESS THAN (2033),
            PARTITION p2033 VALUES LESS THAN (2034),
            PARTITION p2034 VALUES LESS THAN (2035),
            PARTITION p2035 VALUES LESS THAN (2036),
            PARTITION p2036 VALUES LESS THAN (2037),
            PARTITION p2037 VALUES LESS THAN (2038),
            PARTITION p2038 VALUES LESS THAN (2039),
            PARTITION p2039 VALUES LESS THAN (2040),
            PARTITION p2040 VALUES LESS THAN (2041),
            PARTITION p2041 VALUES LESS THAN (2042),
            PARTITION p2042 VALUES LESS THAN (2043),
            PARTITION p2043 VALUES LESS THAN (2044),
            PARTITION p2044 VALUES LESS THAN (2045),
            PARTITION p2045 VALUES LESS THAN (2046),
            PARTITION p2046 VALUES LESS THAN (2047),
            PARTITION p2047 VALUES LESS THAN (2048),
            PARTITION p2048 VALUES LESS THAN (2049),
            PARTITION p2049 VALUES LESS THAN (2050),
            PARTITION p2050 VALUES LESS THAN (2051)
        );
    """)

def downgrade():
    """Drop contracts table."""
    op.execute("DROP TABLE IF EXISTS contracts;")